// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hyhtfzoqjwywzrtdboyq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh5aHRmem9xand5d3pydGRib3lxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg0NDQ0NDQsImV4cCI6MjA2NDAyMDQ0NH0.poPEqcqP7UPiCZu2DBJlU0_3iIqwQr6cJwHoFo9QFMc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);